services:
  divelog-service-fe:
    build: ./divelog-service-fe
    env_file:
      - ./divelog-service-fe/.env
    ports:
      - "3000:3000"


  
  divelog-service-be:
    build: ./divelog-service-be
    env_file:
      - ./divelog-service-be/.env
    depends_on:
      - mysql
  mysql:
    image: mysql
    env_file:
      - ./mysql/.env