apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
      tier: db
  template:
    metadata:
      labels:
        app: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: mysql
        envFrom:
        - configMapRef:
            name: mysql-configmap
        - secretRef:
            name: mysql-secret
        ports:
        - containerPort: 3306
